### ISSUE TITLE
Generate tokens for users configured for a perf test

### ISSUE THREAD

**Issue by 1t5j0y** [avniproject/avni-perf#1]
Create a Make task to generate tokens for users configured for the test

**Comment by mahalakshme** [comment]
We already have such a make task in client codebase. We can reuse that.

**Comment by 1t5j0y** [comment]
yeah I'm aware and that is the approach I started off with but there are a few issues with reusing it:
1. it is in js and dependent on openchs-idi package whereas perf is a java based project
2. will have tight coupling between perf and client if we reuse the script from there and expect perf to be in a certain directory relative to client

**Comment by 1t5j0y** [comment]
Changed the approach to generate tokens during the simulation if not provided in the csv to simplify execution steps.
